In [1]:
import pandas as pd
df=pd.read_csv("/data1/home/piyushmishra/Setubandhan/Assign/quora_questions_subset.csv")

In [4]:
df.head()

id  qid1  qid2                                          question1  \
0   0     1     2  What is the step by step guide to invest in sh...   
1   1     3     4  What is the story of Kohinoor (Koh-i-Noor) Dia...   
2   2     5     6  How can I increase the speed of my internet co...   
3   3     7     8  Why am I mentally very lonely? How can I solve...   
4   4     9    10  Which one dissolve in water quikly sugar, salt...   

                                           question2  is_duplicate  
0  What is the step by step guide to invest in sh...             0  
1  What would happen if the Indian government sto...             0  
2  How can Internet speed be increased by hacking...             0  
3  Find the remainder when [math]23^{24}[/math] i...             0  
4            Which fish would survive in salt water?             0

In [103]:
input=[]
input1=[]
for i in range(df.shape[0]):
    sent=df.iloc[i]['question1']+','+df.iloc[i]['question2']
    n=[sent]
    input.append(n)
    n=[]
    n.append(df.iloc[i]['question1'])
    n.append(df.iloc[i]['question2'])
    input1.append(n)

## Cross-Encoder

In [11]:
from sentence_transformers.cross_encoder import CrossEncoder
model = CrossEncoder('bert-base-uncased')
scores = model.predict(input)

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model tha

In [14]:
scores

array([0.28025922, 0.27901313, 0.2859418 , 0.32864764, 0.28998792,
       0.2914392 , 0.31832182, 0.2922318 , 0.29578698, 0.30335608,
       0.28303036, 0.2948082 , 0.29381227, 0.29399362, 0.27389133,
       0.29365405, 0.3100008 , 0.29500666, 0.2917065 , 0.3064341 ,
       0.28243995, 0.32079625, 0.31159604, 0.30469424, 0.31522754,
       0.2736362 , 0.2916716 , 0.28447613, 0.2838558 , 0.32461882,
       0.28899312, 0.3082673 , 0.29079553, 0.2893568 , 0.28666744,
       0.281445  , 0.26749513, 0.30985275, 0.29844   , 0.27483433,
       0.28224066, 0.3042697 , 0.29304802, 0.29276356, 0.28645065,
       0.2705678 , 0.3148494 , 0.29723585, 0.27559936, 0.30821005,
       0.2866774 , 0.29146475, 0.3097419 , 0.28784284, 0.30063662,
       0.31042516, 0.30158174, 0.2830566 , 0.28010005, 0.30342752,
       0.30581096, 0.297889  , 0.28724766, 0.304025  , 0.29289836,
       0.29355112, 0.3081818 , 0.2859195 , 0.29404375, 0.28747794,
       0.2880465 , 0.29136088, 0.2978531 , 0.29731116, 0.29114

## SBERT

In [25]:
sentences1=list(df['question1'])
sentences2=list(df['question2'])

In [26]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')



#Compute embedding for both lists
embeddings1 = model.encode(sentences1, convert_to_tensor=True)
embeddings2 = model.encode(sentences2, convert_to_tensor=True)

#Compute cosine-similarities
cosine_scores = util.cos_sim(embeddings1, embeddings2)

#Output the pairs with their score
for i in range(len(sentences1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i], sentences2[i], cosine_scores[i][i]))

What is the step by step guide to invest in share market in india? 		 What is the step by step guide to invest in share market? 		 Score: 0.9123
What is the story of Kohinoor (Koh-i-Noor) Diamond? 		 What would happen if the Indian government stole the Kohinoor (Koh-i-Noor) diamond back? 		 Score: 0.6550
How can I increase the speed of my internet connection while using a VPN? 		 How can Internet speed be increased by hacking through DNS? 		 Score: 0.5155
Why am I mentally very lonely? How can I solve it? 		 Find the remainder when [math]23^{24}[/math] is divided by 24,23? 		 Score: 0.1041
Which one dissolve in water quikly sugar, salt, methane and carbon di oxide? 		 Which fish would survive in salt water? 		 Score: 0.3253
Astrology: I am a Capricorn Sun Cap moon and cap rising...what does that say about me? 		 I'm a triple Capricorn (Sun, Moon and ascendant in Capricorn) What does this say about me? 		 Score: 0.8375
Should I buy tiago? 		 What keeps childern active and far from phone

In [30]:
#100*100 tensor where the diagonal elements are the similiarity between the sentences given in the csv 
cosine_scores

tensor([[ 0.9123,  0.1147,  0.0963,  ...,  0.0262,  0.2122,  0.0382],
        [-0.0059,  0.6550,  0.0243,  ...,  0.2108, -0.0634,  0.0108],
        [ 0.0546, -0.1372,  0.5155,  ...,  0.0264,  0.0143,  0.0811],
        ...,
        [ 0.0303,  0.1430,  0.1108,  ...,  0.5902,  0.0454, -0.0441],
        [ 0.1279, -0.1293, -0.0978,  ..., -0.0300,  0.5708,  0.0366],
        [-0.0878, -0.0616,  0.1668,  ...,  0.0172,  0.0284,  0.4791]],
       device='cuda:0')

## Bi-Encoders

In [116]:
from transformers import BertTokenizer, BertModel

import torch


#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


# Sentences we want sentence embeddings for
sentences = ['What is the step by step guide to invest in share market in india? ', 'What is the step by step guide to invest in share market?']

# Load model from HuggingFace Hub
# tokenizer = AutoTokenizer.from_pretrained('sts-GBERT-bi-encoder')
# model = AutoModel.from_pretrained('sts-GBERT-bi-encoder')

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')
score=[]
# Tokenize sentences
for i in range(len(input1)):
    encoded_input = tokenizer(input1[i], padding=True, truncation=True, return_tensors='pt')

    # Compute token embeddings
    with torch.no_grad():
        model_output = model(**encoded_input)

    # Perform pooling. In this case, max pooling.
    sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

    print("Sentence embeddings:")
    print(sentence_embeddings)
    cosine_scores = util.cos_sim(sentence_embeddings[0], sentence_embeddings[1])
    score.append(cosine_scores.item())

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Sentence embeddings:
tensor([[ 0.0744, -0.3269, -0.0529,  ..., -0.3176,  0.2509, -0.0072],
        [ 0.1697, -0.1154,  0.0259,  ..., -0.2805,  0.1627,  0.1974]])
Sentence embeddings:
tensor([[-0.0189, -0.0803, -0.1832,  ..., -0.1722,  0.4370, -0.0365],
        [ 0.2055, -0.1955, -0.2088,  ..., -0.3583,  0.1617, -0.0256]])
Sentence embeddings:
tensor([[ 0.1238, -0.0029,  0.1179,  ..., -0.3461,  0.0177,  0.6082],
        [ 0.3250, -0.0396, -0.1796,  ..., -0.4258,  0.0532,  0.5035]])
Sentence embeddings:
tensor([[-0.3157,  0.4559,  0.0919,  ..., -0.2604,  0.1364,  0.2113],
        [ 0.1097, -0.1797,  0.4573,  ..., -0.5117,  0.0494,  0.5423]])
Sentence embeddings:
tensor([[-0.0725,  0.5681,  0.1450,  ..., -0.5513,  0.2953,  0.2626],
        [ 0.0901, -0.1247, -0.3498,  ..., -0.4124, -0.0048, -0.0435]])
Sentence embeddings:
tensor([[ 0.2602,  0.4011,  0.3074,  ...,  0.0228,  0.2105,  0.2219],
        [ 0.1718,  0.3134,  0.4223,  ..., -0.1321,  0.1672,  0.0944]])
Sentence embeddings:
tensor(

In [118]:
score

[0.9597508311271667,
 0.8796856999397278,
 0.8824726343154907,
 0.5379066467285156,
 0.6742489337921143,
 0.8740227818489075,
 0.5876770615577698,
 0.8807622194290161,
 0.7714179158210754,
 0.828769862651825,
 0.6193062663078308,
 0.9015946984291077,
 0.9573376178741455,
 0.9582241177558899,
 0.9895089864730835,
 0.846177339553833,
 0.9828141331672668,
 0.8590032458305359,
 0.9212809205055237,
 0.9654505252838135,
 0.866264283657074,
 0.8337029218673706,
 0.8180512189865112,
 0.7029927968978882,
 0.8206297159194946,
 0.9730756878852844,
 0.8953811526298523,
 0.8434070944786072,
 0.938932478427887,
 0.6180237531661987,
 0.8665691614151001,
 0.7707244753837585,
 0.8932883143424988,
 0.6265673041343689,
 0.9333825707435608,
 0.8338425755500793,
 0.9169002771377563,
 0.758887529373169,
 0.8264712691307068,
 0.8252191543579102,
 0.6708981394767761,
 0.9704101085662842,
 0.9971421360969543,
 0.7745016813278198,
 0.9316615462303162,
 0.8912074565887451,
 0.4633691906929016,
 0.834494948387146